-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         10.2.10-MariaDB-log - mariadb.org binary distribution
-- SO del servidor:              Win64
-- HeidiSQL Versión:             9.5.0.5433
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- Volcando estructura para tabla sme.countries
DROP TABLE IF EXISTS `countries`;
CREATE TABLE IF NOT EXISTS `countries` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `country_code` varchar(6) NOT NULL DEFAULT '',
  `country_name` varchar(150) NOT NULL,
  `abbreviation` varchar(6) NOT NULL,
  `currency` varchar(6) NOT NULL,
  `image` varchar(120) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE KEY `pais` (`country_code`) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=247 DEFAULT CHARSET=utf8 ROW_FORMAT=DYNAMIC;

-- Volcando datos para la tabla sme.countries: ~223 rows (aproximadamente)
/*!40000 ALTER TABLE `countries` DISABLE KEYS */;
INSERT INTO `countries` (`id`, `country_code`, `country_name`, `abbreviation`, `currency`, `image`) VALUES
	(1, '93', 'Afganistán', 'AFG', '$', 'afganistan.png'),
	(2, '355', 'Albania', 'ALB', '$', 'albania.png'),
	(3, '49', 'Alemania', 'DEU', '$', 'alemania.png'),
	(4, '213', 'Algeria', 'DZA', '$', 'algeria.png'),
	(5, '376', 'Andorra', 'AND', '$', 'andorra.png'),
	(6, '244', 'Angola', 'AGO', '$', 'angola.png'),
	(7, '1 264', 'Anguila', 'AIA', '$', 'anguila.png'),
	(8, '672', 'Antártida', 'ATA', '$', 'antartida.png'),
	(9, '1 268', 'Antigua y Barbuda', 'ATG', '$', 'antigua y barbuda.png'),
	(10, '599', 'Antillas Neerlandesas', 'ANT', '$', 'antillas neerlandesas.png'),
	(11, '966', 'Arabia Saudita', 'SAU', '$', 'arabia saudita.png'),
	(12, '54', 'Argentina', 'ARG', '$', 'argentina.png'),
	(13, '374', 'Armenia', 'ARM', '$', 'armenia.png'),
	(14, '297', 'Aruba', 'ABW', '$', 'aruba.png'),
	(15, '61', 'Australia', 'AUS', '$', 'australia.png'),
	(16, '43', 'Austria', 'AUT', '$', 'austria.png'),
	(17, '994', 'Azerbayán', 'AZE', '$', 'azerbayan.png'),
	(18, '32', 'Bélgica', 'BEL', '$', 'belgica.png'),
	(19, '1 242', 'Bahamas', 'BHS', '$', 'bahamas.png'),
	(20, '973', 'Bahrein', 'BHR', '$', 'bahrein.png'),
	(21, '880', 'Bangladesh', 'BGD', '$', 'bangladesh.png'),
	(22, '1 246', 'Barbados', 'BRB', '$', 'barbados.png'),
	(23, '501', 'Belice', 'BLZ', '$', 'belice.png'),
	(24, '229', 'Benín', 'BEN', '$', 'benin.png'),
	(25, '975', 'Bhután', 'BTN', '$', 'bhutan.png'),
	(26, '375', 'Bielorrusia', 'BLR', '$', 'bielorrusia.png'),
	(27, '95', 'Birmania', 'MMR', '$', 'birmania.png'),
	(28, '591', 'Bolivia', 'BOL', '$', 'bolivia.png'),
	(29, '387', 'Bosnia y Herzegovina', 'BIH', '$', 'bosnia y herzegovina.png'),
	(30, '267', 'Botsuana', 'BWA', '$', 'botsuana.png'),
	(31, '55', 'Brasil', 'BRA', '$', 'brasil.png'),
	(32, '673', 'Brunéi', 'BRN', '$', 'brunei.png'),
	(33, '359', 'Bulgaria', 'BGR', '$', 'bulgaria.png'),
	(34, '226', 'Burkina Faso', 'BFA', '$', 'burkina faso.png'),
	(35, '257', 'Burundi', 'BDI', '$', 'burundi.png'),
	(36, '238', 'Cabo Verde', 'CPV', '$', 'cabo verde.png'),
	(37, '855', 'Camboya', 'KHM', '$', 'camboya.png'),
	(38, '237', 'Camerún', 'CMR', '$', 'camerun.png'),
	(39, '1', 'Canadá', 'CAN', '$', 'canada.png'),
	(40, '235', 'Chad', 'TCD', '$', 'chad.png'),
	(41, '56', 'Chile', 'CHL', '$', 'chile.png'),
	(42, '86', 'China', 'CHN', '$', 'china.png'),
	(43, '357', 'Chipre', 'CYP', '$', 'chipre.png'),
	(44, '39', 'Ciudad del Vaticano', 'VAT', '$', 'ciudad del vaticano.png'),
	(45, '57', 'Colombia', 'COL', '$', 'colombia.png'),
	(46, '269', 'Comoras', 'COM', '$', 'comoras.png'),
	(47, '242', 'Congo', 'COG', '$', 'congo.png'),
	(48, '243', 'Congo', 'COD', '$', 'congo.png'),
	(49, '850', 'Corea del Norte', 'PRK', '$', 'corea del norte.png'),
	(50, '82', 'Corea del Sur', 'KOR', '$', 'corea del sur.png'),
	(51, '225', 'Costa de Marfil', 'CIV', '$', 'costa de marfil.png'),
	(52, '506', 'Costa Rica', 'CRI', '$', 'costa rica.png'),
	(53, '385', 'Croacia', 'HRV', '$', 'croacia.png'),
	(54, '53', 'Cuba', 'CUB', '$', 'cuba.png'),
	(55, '45', 'Dinamarca', 'DNK', '$', 'dinamarca.png'),
	(56, '1 767', 'Dominica', 'DMA', '$', 'dominica.png'),
	(57, '593', 'Ecuador', 'ECU', '$', 'ecuador.png'),
	(58, '20', 'Egipto', 'EGY', '$', 'egipto.png'),
	(59, '503', 'El Salvador', 'SLV', '$', 'el salvador.png'),
	(60, '971', 'Emiratos Árabes Unidos', 'ARE', '$', 'emiratos arabes unidos.png'),
	(61, '291', 'Eritrea', 'ERI', '$', 'eritrea.png'),
	(62, '421', 'Eslovaquia', 'SVK', '$', 'eslovaquia.png'),
	(63, '386', 'Eslovenia', 'SVN', '$', 'eslovenia.png'),
	(64, '34', 'España', 'ESP', '$', 'españa.png'),
	(66, '372', 'Estonia', 'EST', '$', 'estonia.png'),
	(67, '251', 'Etiopía', 'ETH', '$', 'etiopia.png'),
	(68, '63', 'Filipinas', 'PHL', '$', 'filipinas.png'),
	(69, '358', 'Finlandia', 'FIN', '$', 'finlandia.png'),
	(70, '679', 'Fiyi', 'FJI', '$', 'fiyi.png'),
	(71, '33', 'Francia', 'FRA', '$', 'francia.png'),
	(72, '241', 'Gabón', 'GAB', '$', 'gabon.png'),
	(73, '220', 'Gambia', 'GMB', '$', 'gambia.png'),
	(74, '995', 'Georgia', 'GEO', '$', 'georgia.png'),
	(75, '233', 'Ghana', 'GHA', '$', 'ghana.png'),
	(76, '350', 'Gibraltar', 'GIB', '$', 'gibraltar.png'),
	(77, '1 473', 'Granada', 'GRD', '$', 'granada.png'),
	(78, '30', 'Grecia', 'GRC', '$', 'grecia.png'),
	(79, '299', 'Groenlandia', 'GRL', '$', 'groenlandia.png'),
	(80, '', 'Guadalupe', 'GLP', '$', 'guadalupe.png'),
	(81, '1 671', 'Guam', 'GUM', '$', 'guam.png'),
	(82, '502', 'Guatemala', 'GTM', '$', 'guatemala.png'),
	(85, '224', 'Guinea', 'GIN', '$', 'guinea.png'),
	(86, '240', 'Guinea Ecuatorial', 'GNQ', '$', 'guinea ecuatorial.png'),
	(87, '245', 'Guinea-Bissau', 'GNB', '$', 'guinea-bissau.png'),
	(88, '592', 'Guyana', 'GUY', '$', 'guyana.png'),
	(89, '509', 'Haití', 'HTI', '$', 'haiti.png'),
	(90, '504', 'Honduras', 'HND', '$', 'honduras.png'),
	(91, '852', 'Hong kong', 'HKG', '$', 'hong kong.png'),
	(92, '36', 'Hungría', 'HUN', '$', 'hungria.png'),
	(93, '91', 'India', 'IND', '$', 'india.png'),
	(94, '62', 'Indonesia', 'IDN', '$', 'indonesia.png'),
	(95, '98', 'Irán', 'IRN', '$', 'iran.png'),
	(96, '964', 'Irak', 'IRQ', '$', 'irak.png'),
	(97, '353', 'Irlanda', 'IRL', '$', 'irlanda.png'),
	(99, '44', 'Isla de Man', 'IMN', '$', 'isla de man.png'),
	(102, '354', 'Islandia', 'ISL', '$', 'islandia.png'),
	(103, '1 441', 'Islas Bermudas', 'BMU', '$', 'islas bermudas.png'),
	(104, '1 345', 'Islas Caimán', 'CYM', '$', 'islas caiman.png'),
	(106, '682', 'Islas Cook', 'COK', '$', 'islas cook.png'),
	(108, '298', 'Islas Feroe', 'FRO', '$', 'islas feroe.png'),
	(111, '960', 'Islas Maldivas', 'MDV', '$', 'islas maldivas.png'),
	(112, '500', 'Islas Malvinas', 'FLK', '$', 'islas malvinas.png'),
	(113, '1 670', 'Islas Marianas del Norte', 'MNP', '$', 'islas marianas del norte.png'),
	(114, '692', 'Islas Marshall', 'MHL', '$', 'islas marshall.png'),
	(115, '870', 'Islas Pitcairn', 'PCN', '$', 'islas pitcairn.png'),
	(116, '677', 'Islas Salomón', 'SLB', '$', 'islas salomon.png'),
	(117, '1 649', 'Islas Turcas y Caicos', 'TCA', '$', 'islas turcas y caicos.png'),
	(119, '1 284', 'Islas Vírgenes Británicas', 'VG', '$', 'islas virgenes britanicas.png'),
	(120, '1 340', 'Islas Vírgenes de los Estados Unidos', 'VIR', '$', 'islas virgenes de los estados unidos.png'),
	(121, '972', 'Israel', 'ISR', '$', 'israel.png'),
	(123, '1 876', 'Jamaica', 'JAM', '$', 'jamaica.png'),
	(124, '81', 'Japón', 'JPN', '$', 'japon.png'),
	(126, '962', 'Jordania', 'JOR', '$', 'jordania.png'),
	(127, '7', 'Kazajistán', 'KAZ', '$', 'kazajistan.png'),
	(128, '254', 'Kenia', 'KEN', '$', 'kenia.png'),
	(129, '996', 'Kirgizstán', 'KGZ', '$', 'kirgizstan.png'),
	(130, '686', 'Kiribati', 'KIR', '$', 'kiribati.png'),
	(131, '965', 'Kuwait', 'KWT', '$', 'kuwait.png'),
	(132, '961', 'Líbano', 'LBN', '$', 'libano.png'),
	(133, '856', 'Laos', 'LAO', '$', 'laos.png'),
	(134, '266', 'Lesoto', 'LSO', '$', 'lesoto.png'),
	(135, '371', 'Letonia', 'LVA', '$', 'letonia.png'),
	(136, '231', 'Liberia', 'LBR', '$', 'liberia.png'),
	(137, '218', 'Libia', 'LBY', '$', 'libia.png'),
	(138, '423', 'Liechtenstein', 'LIE', '$', 'liechtenstein.png'),
	(139, '370', 'Lituania', 'LTU', '$', 'lituania.png'),
	(140, '352', 'Luxemburgo', 'LUX', '$', 'luxemburgo.png'),
	(141, '52', 'México', 'MEX', '$', 'mexico.png'),
	(142, '377', 'Mónaco', 'MCO', '$', 'monaco.png'),
	(143, '853', 'Macao', 'MAC', '$', 'macao.png'),
	(144, '389', 'Macedônia', 'MKD', '$', 'macedônia.png'),
	(145, '261', 'Madagascar', 'MDG', '$', 'madagascar.png'),
	(146, '60', 'Malasia', 'MYS', '$', 'malasia.png'),
	(147, '265', 'Malawi', 'MWI', '$', 'malawi.png'),
	(148, '223', 'Mali', 'MLI', '$', 'mali.png'),
	(149, '356', 'Malta', 'MLT', '$', 'malta.png'),
	(150, '212', 'Marruecos', 'MAR', '$', 'marruecos.png'),
	(152, '230', 'Mauricio', 'MUS', '$', 'mauricio.png'),
	(153, '222', 'Mauritania', 'MRT', '$', 'mauritania.png'),
	(154, '262', 'Mayotte', 'MYT', '$', 'mayotte.png'),
	(155, '691', 'Micronesia', 'FSM', '$', 'micronesia.png'),
	(156, '373', 'Moldavia', 'MDA', '$', 'moldavia.png'),
	(157, '976', 'Mongolia', 'MNG', '$', 'mongolia.png'),
	(158, '382', 'Montenegro', 'MNE', '$', 'montenegro.png'),
	(159, '1 664', 'Montserrat', 'MSR', '$', 'montserrat.png'),
	(160, '258', 'Mozambique', 'MOZ', '$', 'mozambique.png'),
	(161, '264', 'Namibia', 'NAM', '$', 'namibia.png'),
	(162, '674', 'Nauru', 'NRU', '$', 'nauru.png'),
	(163, '977', 'Nepal', 'NPL', '$', 'nepal.png'),
	(164, '505', 'Nicaragua', 'NIC', '$', 'nicaragua.png'),
	(165, '227', 'Niger', 'NER', '$', 'niger.png'),
	(166, '234', 'Nigeria', 'NGA', '$', 'nigeria.png'),
	(167, '683', 'Niue', 'NIU', '$', 'niue.png'),
	(168, '47', 'Noruega', 'NOR', '$', 'noruega.png'),
	(169, '687', 'Nueva Caledonia', 'NCL', '$', 'nueva caledonia.png'),
	(170, '64', 'Nueva Zelanda', 'NZL', '$', 'nueva zelanda.png'),
	(171, '968', 'Omán', 'OMN', '$', 'oman.png'),
	(172, '31', 'Países Bajos', 'NLD', '$', 'paises bajos.png'),
	(173, '92', 'Pakistán', 'PAK', '$', 'pakistan.png'),
	(174, '680', 'Palau', 'PLW', '$', 'palau.png'),
	(176, '507', 'Panamá', 'PAN', '$', 'panama.png'),
	(177, '675', 'Papúa Nueva Guinea', 'PNG', '$', 'papua nueva guinea.png'),
	(178, '595', 'Paraguay', 'PRY', '$', 'paraguay.png'),
	(179, '51', 'Perú', 'PER', '$', 'peru.png'),
	(180, '689', 'Polinesia Francesa', 'PYF', '$', 'polinesia francesa.png'),
	(181, '48', 'Polonia', 'POL', '$', 'polonia.png'),
	(182, '351', 'Portugal', 'PRT', '$', 'portugal.png'),
	(184, '974', 'Qatar', 'QAT', '$', 'qatar.png'),
	(186, '236', 'República Centroafricana', 'CAF', '$', 'republica centroafricana.png'),
	(187, '420', 'República Checa', 'CZE', '$', 'republica checa.png'),
	(188, '1 809', 'República Dominicana', 'DOM', '$', 'republica dominicana.png'),
	(190, '250', 'Ruanda', 'RWA', '$', 'ruanda.png'),
	(191, '40', 'Rumanía', 'ROU', '$', 'rumania.png'),
	(194, '685', 'Samoa', 'WSM', '$', 'samoa.png'),
	(195, '1 684', 'Samoa Americana', 'ASM', '$', 'samoa americana.png'),
	(196, '590', 'San Bartolomé', 'BLM', '$', 'san bartolome.png'),
	(197, '1 869', 'San Cristóbal y Nieves', 'KNA', '$', 'san cristobal y nieves.png'),
	(198, '378', 'San Marino', 'SMR', '$', 'san marino.png'),
	(199, '1 599', 'San Martín (Francia)', 'MAF', '$', 'san martin (francia).png'),
	(200, '508', 'San Pedro y Miquelón', 'SPM', '$', 'san pedro y miquelon.png'),
	(201, '1 784', 'San Vicente y las Granadinas', 'VCT', '$', 'san vicente y las granadinas.png'),
	(202, '290', 'Santa Elena', 'SHN', '$', 'santa elena.png'),
	(203, '1 758', 'Santa Lucía', 'LCA', '$', 'santa lucia.png'),
	(204, '239', 'Santo Tomé y Príncipe', 'STP', '$', 'santo tome y principe.png'),
	(205, '221', 'Senegal', 'SEN', '$', 'senegal.png'),
	(206, '381', 'Serbia', 'SRB', '$', 'serbia.png'),
	(207, '248', 'Seychelles', 'SYC', '$', 'seychelles.png'),
	(208, '232', 'Sierra Leona', 'SLE', '$', 'sierra leona.png'),
	(209, '65', 'Singapur', 'SGP', '$', 'singapur.png'),
	(210, '963', 'Siria', 'SYR', '$', 'siria.png'),
	(211, '252', 'Somalia', 'SOM', '$', 'somalia.png'),
	(212, '94', 'Sri lanka', 'LKA', '$', 'sri lanka.png'),
	(213, '27', 'Sudáfrica', 'ZAF', '$', 'sudafrica.png'),
	(214, '249', 'Sudán', 'SDN', '$', 'sudan.png'),
	(215, '46', 'Suecia', 'SWE', '$', 'suecia.png'),
	(216, '41', 'Suiza', 'CHE', '$', 'suiza.png'),
	(217, '597', 'Surinám', 'SUR', '$', 'surinam.png'),
	(219, '268', 'Swazilandia', 'SWZ', '$', 'swazilandia.png'),
	(220, '992', 'Tadjikistán', 'TJK', '$', 'tadjikistan.png'),
	(221, '66', 'Tailandia', 'THA', '$', 'tailandia.png'),
	(222, '886', 'Taiwán', 'TWN', '$', 'taiwan.png'),
	(223, '255', 'Tanzania', 'TZA', '$', 'tanzania.png'),
	(226, '670', 'Timor Oriental', 'TLS', '$', 'timor oriental.png'),
	(227, '228', 'Togo', 'TGO', '$', 'togo.png'),
	(228, '690', 'Tokelau', 'TKL', '$', 'tokelau.png'),
	(229, '676', 'Tonga', 'TON', '$', 'tonga.png'),
	(230, '1 868', 'Trinidad y Tobago', 'TTO', '$', 'trinidad y tobago.png'),
	(231, '216', 'Tunez', 'TUN', '$', 'tunez.png'),
	(232, '993', 'Turkmenistán', 'TKM', '$', 'turkmenistan.png'),
	(233, '90', 'Turquía', 'TUR', '$', 'turquia.png'),
	(234, '688', 'Tuvalu', 'TUV', '$', 'tuvalu.png'),
	(235, '380', 'Ucrania', 'UKR', '$', 'ucrania.png'),
	(236, '256', 'Uganda', 'UGA', '$', 'uganda.png'),
	(237, '598', 'Uruguay', 'URY', '$', 'uruguay.png'),
	(238, '998', 'Uzbekistán', 'UZB', '$', 'uzbekistan.png'),
	(239, '678', 'Vanuatu', 'VUT', '$', 'vanuatu.png'),
	(240, '58', 'Venezuela', 'VEN', '$', 'venezuela.png'),
	(241, '84', 'Vietnam', 'VNM', '$', 'vietnam.png'),
	(242, '681', 'Wallis y Futuna', 'WLF', '$', 'wallis y futuna.png'),
	(243, '967', 'Yemen', 'YEM', '$', 'yemen.png'),
	(244, '253', 'Yibuti', 'DJI', '$', 'yibuti.png'),
	(245, '260', 'Zambia', 'ZMB', '$', 'zambia.png'),
	(246, '263', 'Zimbabue', 'ZWE', '$', 'zimbabue.png');
/*!40000 ALTER TABLE `countries` ENABLE KEYS */;

/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IF(@OLD_FOREIGN_KEY_CHECKS IS NULL, 1, @OLD_FOREIGN_KEY_CHECKS) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
